(setq myMagicNumber 5)
(setq myList '(1 3 4 2 4 6))
(defun myPlus (arg)
    (+ arg myMagicNumber)
)
(defun myMult (arg)
    (* arg myMagicNumber)
)
(defun myPair (arg)
    (list arg myMagicNumber)
)
(defun myMap (myFunc list)
(cond
    ((NULL list) NIL)
    (T (cons (funcall myFunc (CAR list)) (myMap myFunc (CDR list))))
)
)
(print(myMap 'myPlus myList))
(print(myMap 'myMult myList))
(print(myMap 'myPair myList))